# Generated by Django 6.0.6 on 2026-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=100)),
                ('industry_sector', models.CharField(max_length=150)),
                ('gst_identification_number', models.CharField(max_length=50)),
                ('corporate_website', models.URLField(blank=True, null=True)),
                ('corporate_work_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('contact_officer_full_name', models.CharField(max_length=255)),
                ('corporate_designation', models.CharField(max_length=150)),
                ('mobile_contact_phone', models.CharField(max_length=20)),
                ('credentials_outbox_email', models.EmailField(max_length=254)),
                ('detailed_street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('emergency_number', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_pincode', models.CharField(max_length=20)),
                ('number_of_sites', models.PositiveIntegerField(default=1)),
                ('total_buildings_complex', models.PositiveIntegerField(default=1)),
                ('pre_onboarded_core_roster_count', models.PositiveIntegerField(default=0)),
                ('workforce_shifts_strength', models.PositiveIntegerField(default=0)),
                ('initial_facility_assets_count', models.PositiveIntegerField(default=0)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
